summon villager ~ ~ ~ {Invulnerable:1b,NoAI:0b,VillagerData:{level:99,profession:"minecraft:toolsmith",type:"minecraft:plains"}}

# Mya 1.0 Doll

data modify entity 091ac14d-b24d-44de-9444-646cc746b387 Offers.Recipes append value {rewardExp:1b,maxUses:1000,xp:10,priceMultiplier:0f,specialPrice:0,demand:0,buy:{id:"minecraft:diamond",count:55},sell:{id:"minecraft:stick",count:1,components:{"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"米亞 1.0 公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}', '{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}'],"minecraft:custom_model_data":{strings:[mya_doll]}}}}

# Nyan Doll

data modify entity 091ac14d-b24d-44de-9444-646cc746b387 Offers.Recipes append value {rewardExp:1b,maxUses:1000,xp:10,priceMultiplier:0f,specialPrice:0,demand:0,buy:{id:"minecraft:diamond",count:55},sell:{id:"minecraft:stick",count:1,components:{"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"小貓公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}', '{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}'],"minecraft:custom_model_data":{strings:[nyan_doll]}}}}

# Gummy Doll

data modify entity 091ac14d-b24d-44de-9444-646cc746b387 Offers.Recipes append value {rewardExp:1b,maxUses:1000,xp:10,priceMultiplier:0f,specialPrice:0,demand:0,buy:{id:"minecraft:diamond",count:55},sell:{id:"minecraft:stick",count:1,components:{"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"甘米公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}', '{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}'],"minecraft:custom_model_data":{strings:[gummy_doll]}}}}

# 米亞 3.0 公式服公仔

data modify entity 091ac14d-b24d-44de-9444-646cc746b387 Offers.Recipes append value {rewardExp:1b,maxUses:1000,xp:10,priceMultiplier:0f,specialPrice:0,demand:0,buy:{id:"minecraft:diamond",count:55},sell:{id:"minecraft:stick",count:1,components:{"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"米亞 3.0 公式服公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}', '{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}'],"minecraft:custom_model_data":{strings:[mya_three_zero_doll]}}}}

# Convert from old doll to new doll metadata: Test for item with specific metadata

# Convert 米亞 1.0 公仔
execute positioned -88 75 -11 as @e[type=item,distance=..2] if data entity @s Item{id:"minecraft:stick",components:{"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"米亞 1.0 公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}','{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}']}} run data modify entity @s Item.components merge value {"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"米亞 1.0 公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}', '{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}'],"minecraft:custom_model_data":{strings:[mya_doll]}}

# Convert 小貓公仔
execute positioned -88 75 -11 as @e[type=item,distance=..2] if data entity @s Item{id:"minecraft:stick",components:{"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"小貓公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}', '{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}']}} run data modify entity @s Item.components merge value {"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"小貓公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}','{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}'],"minecraft:custom_model_data":{"strings":["nyan_doll"]}}

# Convert 甘米公仔
execute positioned -88 75 -11 as @e[type=item,distance=..2] if data entity @s Item{id:"minecraft:stick",components:{"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"甘米公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}', '{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}']}} run data modify entity @s Item.components merge value {"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"甘米公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}','{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}'],"minecraft:custom_model_data":{"strings":["gummy_doll"]}}

# Convert 米亞 3.0 公式服公仔
execute positioned -88 75 -11 as @e[type=item,distance=..2] if data entity @s Item{id:"minecraft:stick",components:{"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"米亞 3.0 公式服公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}', '{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}']}} run data modify entity @s Item.components merge value {"minecraft:custom_name":'{"bold":false,"color":"#FA8072","italic":false,"obfuscated":false,"strikethrough":false,"text":"米亞 3.0 公式服公仔","underlined":false}',"minecraft:lore":['{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"3D Modeling: 村民","underlined":false}','{"bold":false,"color":"#FAC472","italic":false,"obfuscated":false,"strikethrough":false,"text":"Programming: I\'m error (Sam)","underlined":false}'],"minecraft:custom_model_data":{"strings":["mya_three_zero_doll"]}}

# Remove Trade
data remove entity 091ac14d-b24d-44de-9444-646cc746b387 Offers.Recipes[2]

